# Generated by Django 5.2 on 2025-04-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_userprofile_email_usersignup_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='email',
            field=models.EmailField(blank=True, max_length=10, null=True),
        ),
    ]
