# Generated by Django 5.2 on 2025-04-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0004_alter_userprofile_email_alter_usersignup_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='artworks/')),
                ('category', models.CharField(choices=[('sketch', 'Sketch'), ('portrait', 'Portrait'), ('oil', 'Oil Painting'), ('digital', 'Digital Art')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
