# Generated by Django 5.2 on 2025-04-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0005_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.CharField(choices=[('sketch', 'Sketch'), ('portrait', 'Portrait'), ('oil paint', 'Oil Painting'), ('digital art', 'Digital Art')], max_length=50),
        ),
    ]
