# Generated by Django 5.2 on 2025-04-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0006_alter_artwork_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.CharField(choices=[('Sketches', 'Sketches'), ('Portraits', 'Portraits'), ('Oil Paintings', 'Oil Paintings'), ('Digital Art', 'Digital Art')], max_length=50),
        ),
    ]
