# Generated by Django 5.2 on 2025-04-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0007_alter_artwork_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='height',
            field=models.PositiveIntegerField(default=0, help_text='Height in cm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='width',
            field=models.PositiveIntegerField(default=0, help_text='Width in cm'),
            preserve_default=False,
        ),
    ]
