# Generated by Django 5.2 on 2025-04-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0009_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='artwork',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
