# Generated by Django 5.2 on 2025-04-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0012_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
