# Generated by Django 5.2 on 2025-04-22 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0013_delete_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintings.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paintings.usersignup')),
            ],
        ),
    ]
