# Generated by Django 5.2 on 2025-05-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0015_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='thumbnail_2',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='thumbnail_3',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
    ]
