# Generated by Django 5.2 on 2025-05-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0016_artwork_thumbnail_2_artwork_thumbnail_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='thumbnail_4',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
    ]
