# Generated by Django 5.2 on 2026-02-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0017_artwork_thumbnail_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersignup',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='phoneorusername',
            field=models.CharField(max_length=100),
        ),
    ]
