# Generated by Django 5.2 on 2026-02-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0018_alter_usersignup_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phoneorusername',
            field=models.CharField(max_length=100),
        ),
    ]
