# Generated by Django 5.2 on 2026-02-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0019_alter_userprofile_phoneorusername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phoneorusername',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='phoneorusername',
            field=models.CharField(max_length=15),
        ),
    ]
